# Site settings
author: Nick Nobile
title: Algo's Rhythm's
header-img: img/home-bg.png
email: nickcnobile@gmail.com
copyright_name: Nick Nobile
description: > # this means to ignore newlines until "baseurl:"
  The story of one man's journey to learn, decipher, and manipulate code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nnobile

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
